/*jslint node: true */
"use strict";

// Seed math

exports.random = x => {
    return x * Math.random();
};

exports.randomAngle = () => {
    return Math.PI * 2 * Math.random();
};

exports.randomRange = (min, max) => {
    return Math.random() * (max - min) + min;
};

exports.irandom = i => {
    let max = Math.floor(i);
    return Math.floor(Math.random() * (max + 1)); //Inclusive
};

exports.irandomRange = (min, max) => {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1)) + min; //Inclusive
};

exports.gauss = (mean, deviation) => {
    let x1, x2, w;
    do {
        x1 = 2*Math.random() - 1;
        x2 = 2*Math.random() - 1;
        w = x1 * x1 + x2 * x2;
    } while (0 == w || w >= 1);

    w = Math.sqrt(-2 * Math.log(w) / w);
    return mean + deviation * x1 * w;
};

exports.gaussInverse = (min, max, clustering) => {
    let range = max - min;
    let output = exports.gauss(0, range / clustering);

    while (output < 0) {
        output += range;
    }
    
    while (output > range) {
        output -= range;
    }
    
    return output + min;
};

exports.gaussRing = (radius, clustering) => {
    let r = exports.random(Math.PI * 2);
    let d = exports.gauss(radius, radius*clustering);
    return {
        x: d * Math.cos(r),
        y: d * Math.sin(r),
    };
};

exports.chance = prob => {
    return exports.random(1) < prob;
};

exports.dice = sides => {
    return exports.random(sides) < 1;
};

exports.choose = arr => {
    return arr[exports.irandom(arr.length - 1)];
};

exports.chooseN = (arr, n) => {
    let o = [];
    for (let i=0; i<n; i++) {
        o.push(arr.splice(exports.irandom(arr.length - 1), 1)[0]);
    }
    return o;
};

exports.chooseChance = (...arg) => {
    let totalProb = 0;
    arg.forEach(function(value) { totalProb += value; });
    let answer = exports.random(totalProb);
    for (let i=0; i<arg.length; i++) {
        if (answer<arg[i]) return i;
        answer -= arg[i];
    }
};


exports.chooseBotName = () => {
    return exports.choose([
    "Are u fat",
    "Basket",
    "d",
    "Our world of tanks",
    "Wait this aint diep!",
    "Yes",
    "njdknjndfjksddkjc",
    "Omae wa, mou shindeiru",
    "I crave cheddar",
    "Hello",
    "Move outta my way!",
    "DABABY",
    "Haha! funny ram!!",
    "Peter griffin",
    "Queen Tank",
    "Snow tank",
    "Freeze",
    "Big chungus",
    "GlitCheDtAnK",
    "Vicious Tank",
    "Weeee!",
    "Luma ur trash lol",
    "i will swear word at you",
    "CHEEZZZ!",
    "Alpha",
    "Beta",
    "Indev",
    "STRONG彡",
    "彡",
    "AMOGUS🩸🩸🩸",
    "PasifiK-",
    "woɑrfel",
    "◤Poͥtaͣtͫo◢",
    "[MG]Master OV",
    "♛BANANAS🍌",
    "𝕮ajaha🌌",
    "N🌌 Te☠ming",
    "₩ØℜℒD♛!",
    "Fire",
    "😈Theͥ Bͣoͫss😈",
    "Heяø ⚡ Vσяtєჯ",
    "⚔ƁᙈββŁΣßΛĻŽ༻⊱遊㊣",
    "❰✵❱",
    "♐༻๖ۣ🌺ᗯɪS𝕰𝓒☯🌺༺",
    "👿⇀✨ＭＴＣ✨⇀👿",
    "⚡☠𝓖𝓞𝓛𝓓☠⚡",
    "〖TψT〗☢ ᴬᴳ戀•ᴀssᴀsɪɴ•戀╰‿╯Hjlp",
    "ᴼᴹᴳ🗽",
    "▄︻┻═┳一",
    "╭∩╮(◣_◢)╭∩╮",
    "▄︻̷̿┻̿═━一?βΔŋɠ?",
    "█▬█ █ ▀█▀",
    "ᴹᴷ༗⨀⃝⃟⃞๖ۣ•҉ஓீสัץVͣaͫ₲͕̭̂̌͂̌̾͢Ø",
    "turkey",
    "pecho frio",
    "riBer",
    "Belgrano",
    "San Martin",
    'Dominator',
    "Delta",
    "Plasma",
    "Trapper Gunner best tank",
    "Hotel trivago",
    "stemacrk csuventrrt",
    "Ankha",
    "nononononononononono",
    "kilogramo",
    "china",
    "Mark Szucnebirng",
    "Thinkus Binkus",
    "Google",
    "Yahoo",
    "Bing",
    'worldwide-ffa',
    'Atlas',
        'awesomenotawesome',
        'Sonic from gta',
        'Mario Bros',
        'DEADLORD',
        'Waterflame',
        'Stop Watch',
        'Zambค',
        'ɦUniKittyXX_X_Xץ',
        'X_X',
        'rat',
        '! XD ALERT !',
        'arras king',
        'drea34',
        'emulator',
        'mario 65',
        'red luigi',
        'waluigi',
        'guayando',
        'pablo perez',
        'Cesar Vialpando',
        'Cesar guia al bando',
        'CJ',
        'F',
        'Joant',
        'Ü',
        'pewdiepie',
        'tato',
        'tevez',
        'nikocado avocado',
        'dripping',
        '♡Sally♡',
        'sevena',
        '5r',
        'the battle tanks',
        'defend that sanctuary',
        '._.',
        '#SanctuaryLivesMatters',
        'Tri-line',
        'Rulombot',
        'Celestial',
        '555335353',
        '777',
        'juanchoprogamer_xx777_diosdetodojuego_capo_hacker_supremo_elmejor_soltero',
        'PS3',
        'studio',
        'scratch',
        'farando',
    "OPERA GX",
    "BRAVE IS THE BEST BROWSER",
    "Didn't Ask",
    "Don't care",
    "Lagbreaker",
    "Blue Knight",
    "Muzzu",
    "An unnamed tank",
    "Arras",
    "Nimu",
    "Mena S.I.L.D 321 Punthamon",
    "L O L",
    "Chronos",
    "Newton",
    "Sxrh",
    "ItsXario",
    "sarahhh",
    "Richard",
    "Golden",
    "Diamond",
    "Emerald",
    "Ellie Rose",
    "Henry Stickmin",
    "no merecia eso",
    "ARGNETINA",
    "Sos",
    "Fox",
    "king crimson nodoriau",
    "CR",
    "Indiaren",
    "Pepe el Mago",
    "carzy",
    "Fernet",
    "NNN",
    "Gaming",
    "IM PRO",
    "TANK DESTROYER",
    "Zalgo",
    "Xiao",
    "(FR)",
    "WE DO A LITTLE TROLLING",
    "trollface",
    "was not the Impostor",
    "was the Impostor",
    "beep boop badap be doop",
    "The Audacity of this tank",
    "NoNutNovember",
    "Oscar awarded tank",
    "MMMMMM",
    "y u do dis",
    "country roads take me home",
    "Sierra Leone",
    "Do the Tango",
    "always eat Uniform",
    "Victorious tank",
    "Whiskey",
    "X-Ray",
    "tank biology",
    "fake furry",
    "Alice",
    "Bob",
    "Carmen",
    "David",
    "Edith",
    "Freddy",
    "Gustav",
    "Helga",
    "Janet",
    "Lorenzo",
    "Mary",
    "Nora",
    "Olivia",
    "Peter",
    "Queen",
    "Roger",
    "Suzanne",
    "Tommy",
    "Ursula",
    "Vincent",
    "Wilhelm",
    "Xerxes",
    "Yvonne",
    "Zachary",
    "Alpha",
    "Bravo",
    "Charlie",
    "Delta",
    "Echo",
    "Foxtrot",
    "Hotel",
    "India",
    "Juliet",
    "Kilo",
    "Lima",
    "Mike",
    "November",
    "Oscar",
    "Papa",
    "Quebec",
    "Romeo",
    "Sierra",
    "Tango",
    "Uniform",
    "Victor",
    "Whiskey",
    "X-Ray",
    "Yankee",
    "Zulu",
    "Zachary",
    "wheres my burrito",
    "uwu owo",
    "wrong!",
    "what da dog doin?",
    "nobody asked",
    "herobrine, i like balls",
    "get r done",
    "nerf yourself",
    "owo uwu",
    "pounces on you",
    "a knockout!",
    "fart",
    "oh god wrong! has a gun",
    "your local tank",
    "screw kpop",
    "explain how many times you killed us",
    "what a baller",
    "NO CRACKERS GROMIT",
    "Basic",
    "This was a mistake",
    "Victory royale!!11",
    "luma sucks at this game",
    "gib cheddar",
    "if u wanna get with me",
    "bloodlust",
    "a certified hood classic",
    "wduwumduwhdogdyueihws",
    "set gasoline on gasoline",
    "who pooped in my sock?",
    "electrodynamix",
    "QR2",
    "only a small percentage are actually subbed",
    "REMOVE SWITCHAROO",
    "KEEP SWITCHAROO",
    "TWINISUNBALANCEDHHHHE",
    "unnamed",
    "Creeper",
    "Minecraft",
    "Roblox sux",
    "DONT GIVE RICHARDSON TOKEN!",
    "cataclysm",
    "Please team!",
    "[F-22]",
    "i liek ice creanm",
    "TEAM",
    "lost pet",
    "MG SPIN TO TEAM",
    "Arena Closer",
    "me",
    "성우밍",
    "sugoi desu ne kawaii",
    "KYUSHU!",
    "swarmer stormer",
    "balls",
    "pls remove school",
    "mkfdsusidbsj",
    "hi there!",
    "STOP TEAMING!",
    "TEAM FOR PET",
    "Team please i wub you",
    "𝓐𝓷𝓽𝓲-𝓗𝓾𝓷𝓽",
    "Ⓒⓞⓚⓔ",
    "𝗧𝗼𝘁𝗮𝗹𝗹𝘆 𝗻𝗼𝘁 𝗺𝗲𝗮𝗻 𝗯𝗲𝗮𝗻",
    "nerf ai",
    "this is a bot bleep boop",
    "remove this game!",
    "PLS UPDATE",
    "Team with me!",
    "whats the token?",
    "pee",
    "BuildUpSpeedFor12hours",
    "give me token!!",
    "give dev powers pls :3",
    "fitnessgram pacer test",
    "give token or hack",
    "hey stop stealing my kills!",
    "THE REAL SINBADX",
    "FeZTivAL",
    "comically large spoon",
    "skibidi bop mm dada",
    "too fast too funni",
    "and he",
    "yoda_dies.mp3",
    "number 15",
    "burger king foot lettuce",
    "you got a super boots!",
    "and the goes around",
    "when the impostor is sus",
    "truce?",
    "my little pony",
    "baby nut",
    "alvin from alvin and the chimpmunks",
    "goo",
    "Goo, what rhymes with goo? poo! what rhymes with poo? you!",
    "An unnamed tank",
    "Amogus",
    "DERPY WANT MUFFIN",
    "What da dog doin?",
    "SUPER IDOL",
    "bing chilling",
    "where me is go?",
    "Around we go",
    "Kevin Mcleod",
    "Not funny, didnt laugh",
    "dbhfncjeskkz",
    "TOTALLY REAL (100% REAL NO FAKE) DEV TOKEN ARRAS.IO NO CLICKBAIT NO SCAM",
    "developer",
    "TankMaster",
    "Denied.",
    "how about no",
    "deez nuts",
    "kracc bacc",
    "bruh gaming",
    "cheesetouchgaming",
    "poo!",
    "ejj98g9w0foj",
    "PAPA LOUIE DHRFSREkn",
    "GeanaSHUTUPSCDFIOJKN",
    "slaughterhouse",
    "vn",
    "vietnam",
    "stanyoongiordie",
    "jpop over kpop",
    "gimme account now",
    "ip",
    "neeph",
    "x3",
    "absol",
    "oblivion",
    "PEPPA SPRAY",
    "comrade",
    "1234567890",
    "qwertyuiop",
    "ball",
    "square",
    "?",
    "DIEEEEEEEEE",
    "bruh momentus",
    "asdfghjkl",
    "zxcvbnm",
    "831 unvigintillion",
    "ITS OVER 9000!",
    "wha?",
    "perry the platypus?!",
    "tankster.io sucks!!",
    "diep.io better",
    "arras.io better",
    "butdeepinsideourhearts",
    "tankster.io is the worst",
    "halo",
    "blooket",
    "im furry :333",
    "SWITZERLAND",
    "guten tag polen",
    "NO SIGNAL",
    "⚠",
    "give robux",
    "36728",
    "131072",
    "8388608",
    "2147483647",
    "FNF",
    "Pony town",
    "ENGINEER GAMING",
    "s",
    "Ü",
    "Gardevoir",
    "F~",
    "Zlatan",
    "JuegaGerman",
    "Fernanfloo",
    "rawr",
    "neptune",
    "furry",
    "JESUS CHRIST",
    "SKILL ISSUE",
    "Trooper",
    "5",
    "iloveyou",
    "MARIO BE BALLING",
    "Ulises Barrios",
    "SteelKota",
    "t",
    "IMPSOTRO",
    "jdsf9j40j6932141412412412",
         'Alice',
        'Bob',
        'Carmen',
        'David',
        'Edith',
        'Freddy',
        'μ',
        'Helga',
        'Greg',
        'Lorenzo',
        'Mary',
        'Nora',
        'Olivia',
        'Peter',
        'Craig',
        'Roger',
        'Suzanne',
        'Tommy',
        'Ursula',
        'Vincent',
        'Wilhelm',
        'Xerxes',
        'Yvonne',
        'Zachary',
        'Alpha',
        'Bravo',
        '[CR] SONAH',
        'π',
        'ΒΘΪ!!!! ',
        'Hotel',
        'Navy898',
        'Whiskey',
        '[DR] Flanker',        
      'Oh hello there',
     '1337 % 0',
     'hax',
      'n00b',
     'haxor',
      'pro',
      'hacekr',
      'bee',
      'BEGONE',
      'UwU',
      'LOV U <3',
      'g.basic',
      'oof!',
      'Get over here',
      'FALCON PUNCH!',
      'and his name is JOHN CENA!!!!',
      'Busrodah',
      'Srah',
      'orquestra',
      'back to the future',
      'ARENA ENDER',
      'F3RR1_L0V3R_:3',
      'yo m',
    "cope harder",
    "ELRUBIUS",
    "ELDIOSDETODOJUEGO",
    "culo",
    "NO",
    "what",
    "Natsuki",
    "CESAR DEL PLANETA DE LO SIMIO",
    "J",
    "Sinbadx",
    "FireFly",
    "Voizion",
    "NwN",
    "UWU",
    "UWUU",
    "OWO",
    "⚠ NWN ⚠ OWO ⚠ UWU",
    "⚠ OWO",
    "⚠ UWU",
    "UWU ARMY",
    "UWU ARMY!",
    "23",
    "YOUR MOTHER",
    ]);
};

exports.chooseBossName = (code, n) => {
    switch (code) {
    case 'a':
    return exports.chooseN([
          "Archimedes",
          "Akilina",
          "Anastasios",
          "Athena",
          "Alkaios",
          "Amyntas",
          "Aniketos",
          "Artemis",
          "Anaxagoras",
          "Apollon",
          "Apis",
          "Abundantia",
          "MelGarmin",
          "AhmadMel",
          "Alfrtheo",
          "Larbs",
          "Korbloxius",
          "Shando",
          "Shinez",
          "Laslo",
          "Extremis",
          "Insert Tool Noob",
          "D8Dev",
          "Lord Umberhallow",
          "Mr. Tanks IV",
          "Newbiemancer V",
          "Sir Furrysalot IX",
          "Arvenyx",
          "The Crusaders Gladiation",
          "Nokem, the FurTank",
          "Soulstice",
          "Mr. Tanks XV",
          "Revengeance Flareon SDX",
          "Catastrophe",
          "Lord Boss X",
          "Deathwish Furrysalot",
          "Sir Flareon X",
          "Reignburner",
          "Ancalagon Spire ",
          "Terrestrial Nightmare",
          "Ω Volcalis, the Furrysalot Reincarnation",
          "Hellbound Tank",
          "The Bolted Behemoth",
          "Draedalus Ravager",
                "Gargantuar",
          "Juggernaut",
          "Tankbot",
          "Bulletpowder",
          "Tankbomb",
          "Primitive Abundantia",
          "Pentaner",
          "Tyriqia",
          "AhmadMel",
          "Hannya",
          "King Tankwah",
          "Steel Tank",
          "Paladin",
          "Clawdelabra",
          "Amentity",
          "Construtroyer",
          "Arachne",
          "Aurum",
          "Blasitasm",
          "Defender of Reality",
          "Devoratrix",
          "Dharkdowist",
          "Effervescent",
          "Igneothorn",
          "Karhra",
          "Ferozarium Tank",
          "Firelily",
          "Forgotten Beast",
          "Oculord",
          "Portmanteau, The Fusion",
          "Polyphemalus",
          "Mastermind",
          "Monsieur",
          "Siegethorn",
          "Negativitron",
          "Saturn",
          "Neptune",
          "Nyarlathotep",
          "SuperNova",
    ], n);
            case 'negro':
    return exports.chooseN([
          "negro",
          "n-word",
          "black"
    ], n);
    case 'castle':
    return exports.chooseN([
         "Archimedes",
          "Akilina",
          "Anastasios",
          "Athena",
          "Alkaios",
          "Amyntas",
          "Aniketos",
          "Artemis",
          "Anaxagoras",
          "Apollon",
          "Apis",
          "Abundantia",
          "MelGarmin",
          "AhmadMel",
          "Alfrtheo",
          "Larbs",
          "Korbloxius",
          "Shando",
          "Shinez",
          "Laslo",
          "Extremis",
          "Insert Tool Noob",
          "D8Dev",
          "Lord Umberhallow",
          "Mr. Tanks IV",
          "Newbiemancer V",
          "Sir Furrysalot IX",
          "Arvenyx",
          "The Crusaders Gladiation",
          "Nokem, the FurTank",
          "Soulstice",
          "Mr. Tanks XV",
          "Revengeance Flareon SDX",
          "Catastrophe",
          "Lord Boss X",
          "Deathwish Furrysalot",
          "Sir Flareon X",
          "Reignburner",
          "Ancalagon Spire ",
          "Terrestrial Nightmare",
          "Ω Volcalis, the Furrysalot Reincarnation",
          "Hellbound Tank",
          "The Bolted Behemoth",
          "Draedalus Ravager",
    ], n);
    default: return 'God';
    }
};
